update action config

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,10 @@ jobs:
           echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
           chmod 600 ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa.pub
-          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
+          ssh-keyscan -H ${{ secrets.IP }}
+          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts || echo "Failed to write to known_hosts"
+          cat ~/.ssh/known_hosts
+
       - name: Prepare and Deploy Go Application
         run: |
           ssh ${{ secrets.USER_IP }} "
